admin_group_id: -1002381806001

time_to_send:
  - "07:00"
  - "14:00"
  - "20:00"

moderators_ids:
  - 245888700
  - 448098885
  - 1011063055
  - 6227165142
  - 350695012
  - 329631373
  - 1305580230
  - 1067437150
  - 462397607
  - 1617123580
  - 1937902853
  - 350695012
  - 268314946
  - 5409634936
  - 1327936237
